#!/usr/bin/env python

import os
import sys
import optparse

try:
    import GmailNotifier.Main
except ImportError:
    path = os.path.join(os.path.dirname(__file__), '..', 'share', 'gmail-notifier')
    sys.path.insert(0, path)
    import GmailNotifier.Main

if __name__ == '__main__':
    parser = optparse.OptionParser()
    parser.add_option('-d', '--debug', action='store_true', default=False)
    (options, args) = parser.parse_args()
    GmailNotifier.Main.main(debug=options.debug)
