#!/usr/bin/env python

import os
import sys

try:
    import MailIndicator.Main
except ImportError:
    path = os.path.join(os.path.dirname(__file__), '..', 'share', 'gmail-notifier')
    sys.path.insert(0, path)
    import MailIndicator.Main

if __name__ == '__main__':
    MailIndicator.Main.main()
